sonar.projectKey=cloud-engineer-assessment-2026
sonar.projectName=Cloud Engineer Assessment 2026
sonar.sources=.
sonar.exclusions=.git/**,.github/**,Cloud Engineer Assessment 2026.pdf
sonar.sourceEncoding=UTF-8

