apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redemption-deny-by-default
  namespace: redemption
spec:
  podSelector:
    matchLabels:
      app: redemption
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
